spring:
  application:
    name: portfolio
  profiles:
    active: local
  messages:
    basename: errors

  datasource:
    url: jdbc:mariadb://localhost:3306/dbOjtProject
    username: root
    password: jhlee
